Sdev 886 package elnok and add the installation to the install sh script
delmic/elnok pull request #2
Opened 2023-06-21 12:38 UTC by nandishjpatel

Ticket: https://delmic.atlassian.net/browse/SDEV-886

2023-06-21 12:52 UTC, tepals requested changes

2023-06-21 12:52 UTC, tepals commented on debian/changelog
> +  * Initial release for vesrion 1.1
```suggestion
  * Initial release for version 1.1
```

2023-06-21 12:52 UTC, tepals commented on debian/copyright
> + Odemis. If not, see http://www.gnu.org/licenses/.
```suggestion
 ELNOK is free software: you can redistribute it and/or modify it under the
 terms of the GNU General Public License as published by the Free Software
 Foundation, either version 2 of the License, or (at your option) any later
 version.
 .
 ELNOK is distributed in the hope that it will be useful, but WITHOUT ANY
 WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 PARTICULAR PURPOSE. See the GNU General Public License for more details.
 .
 You should have received a copy of the GNU General Public License along with
 ELNOK. If not, see http://www.gnu.org/licenses/.
```

2023-06-21 12:52 UTC, tepals commented on debian/rules
> +	# Just be sure there is no left over from previous egg-info directories
```suggestion
	# Just be sure there is no leftover from previous egg-info directories
```

2023-06-23 09:41 UTC, tepals approved these changes

2023-06-26 14:40 UTC, pieleric requested changes

2023-06-26 14:40 UTC, pieleric commented on debian/control
> +Package: python3-elnok
The package should be called `elnok`. Here, we provide a utility program. We don't care in which language this was written in. You have to add `python3-` for the packages which provide a python module.

2023-07-01 07:23 UTC, pieleric approved these changes

2023-07-01 07:24 UTC, merged